### ISSUE TITLE
Develop in-depth, on-site pace calculator

### ISSUE THREAD

**Issue by xelnia** [wescopeland/kongtrac.kr#25]
1. Can be used to track live games
2. Final data can be saved and attached to a game if it is entered into the database
3. Adjustable parameters
   a. Base values for death points can be assumed before they happen, or left at 0. Future death points    can be also be adjusted (based on past death averages, left at 0, etc.)
   b. A total score can be entered for any board and the calculator will fill automatically fill in previous values if blank (based on assumed averages) and predict pace. Obviously not accurate, but will help when tracking games from mid-point until data can be gathered
   c. Miscellaneous factors can be used: Late-game pace deflation due to fatigue or a change in strategy (switching from two hammers to one on barrels), for example. Deflation will probably require a re-calculation of averages with a new starting point.  
4. Live game data can be compared to previous entries in the database to give a forecast / comparison.
5. Full breakdown of totals and averages with tables and graphs

**Comment by wescopeland** [comment]
Big plans for this, but it's going to be another app that hooks into a kongtrac.kr API and works for multiple games -- not just Donkey Kong. Think LiveSplit, but for scores.
