### ISSUE TITLE
Board averages are not being calculate/displayed for partial levels

### ISSUE THREAD

**Issue by xelnia** [wescopeland/kongtrac.kr#63]
For example. Billy Gaines' recent 810,800 that ends on 21-6. The "Moment" slider only shows up to Level 20, so we can't see how the final 5 boards changed the overall average. 8,200 is the final displayed average, but the actual final average was 8,300 (rounded up from 8,261).

**Comment by wescopeland** [comment]
The sliders only support completed levels. This may be re-addressed in a future patch, but it would require some significant UI code changes to make launch.
