### ISSUE TITLE
Rick Busche Jr. name causing problems?

### ISSUE THREAD

**Issue by xelnia** [wescopeland/kongtrac.kr#69]
His games are in the database, but aren't showing on the scoreboard...I entered it more than once because I didn't realize there was an error.

-K2VH2Q4cT_q-VZbaU4N
-K3Bp0csekTM_P3AZBLA

**Comment by wescopeland** [comment]
DB has been fixed by renaming Rick Busche Jr. to Rick Busche Jr
Periods cause problems in naming ... quick fix for this is to not allow users to enter periods for names when submitting games

**Comment by wescopeland** [comment]
fixed with 0d38dcd
